---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-all
  name: test-all
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-all
  template:
    metadata:
      labels:
        app: test-all
    spec:
      containers:
      - image: rahulait/test-server:latest
        name: test
        ports:
        - name: tcp-1
          containerPort: 4343
          protocol: TCP
        - name: udp-1
          containerPort: 7070
          protocol: UDP
        - name: http-1
          containerPort: 8080
          protocol: TCP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: test-all
  labels:
    app: test-all
spec:
  type: LoadBalancer
  selector:
    app: test-all
  ports:
    - name: udp-1
      protocol: UDP
      port: 7070
      targetPort: 7070
    - name: http-1
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http-2
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: tcp-1
      protocol: TCP
      port: 4343
      targetPort: 4343
  sessionAffinity: None
