---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-udp
  name: test-udp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-udp
  template:
    metadata:
      labels:
        app: test-udp
    spec:
      containers:
      - image: rahulait/test-server:latest
        name: test
        ports:
        - name: udp-1
          containerPort: 7070
          protocol: UDP
        - name: http-1
          containerPort: 80
          protocol: TCP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: test-udp
  labels:
    app: test-udp
spec:
  type: LoadBalancer
  selector:
    app: test-udp
  ports:
    - name: udp-1
      protocol: UDP
      port: 7070
      targetPort: 7070
  sessionAffinity: None
