---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-http
  name: test-http
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-http
  template:
    metadata:
      labels:
        app: test-http
    spec:
      containers:
      - image: rahulait/test-server:latest
        name: test
        ports:
        - name: http-1
          containerPort: 8080
          protocol: TCP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: test-http
  labels:
    app: test-http
spec:
  type: LoadBalancer
  selector:
    app: test-http
  ports:
    - name: http-1
      protocol: TCP
      port: 8080
      targetPort: 8080
  sessionAffinity: None
